#!/usr/bin/env bash

[[ -f "$MODULE_ROOT_DIRECTORY_PATH/.build/$MODULE_NAMESPACE_VALUE.js" ]] && \
mv "$MODULE_ROOT_DIRECTORY_PATH/.build/$MODULE_NAMESPACE_VALUE.js" "$MODULE_ROOT_DIRECTORY_PATH/$MODULE_NAMESPACE_VALUE.js"

[[ -d $TRASH_DIRECTORY ]] &&						\
[[ -d "$MODULE_ROOT_DIRECTORY_PATH/.build" ]] &&	\
mv --force "$MODULE_ROOT_DIRECTORY_PATH/.build" "$TRASH_DIRECTORY";

return 0;
